[package]
name = "rustpython"
version = "0.1.0"
authors = ["Windel Bouwman", "Shing Lyu <shing.lyu@gmail.com>"]

[dependencies]
rustpython_parser = {path = "parser"}
rustpython_vm = {path = "vm/RustPython"}
