[package]
name = "rustpython_vm"
version = "0.1.0"
authors = ["Shing Lyu <shing.lyu@gmail.com>"]

[dependencies]
log = "0.3"
rustpython_parser = {path = "../parser"}
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.26"
