[package]
name = "rustpython_parser"
version = "0.0.1"
authors = [ "Shing Lyu", "Windel Bouwman" ]
build = "build.rs"

[build-dependencies]
lalrpop="0.15.1"

[dependencies]
clap="2.20.0"
env_logger="0.5.10"
lalrpop-util="0.15.1"
log="0.4.1"
py_code_object = { path = "../py_code_object" }
regex="0.2.2"

